name: Upload packages from dist/ to PyPI
description: 'Uses twine to upload packages from dist/ to public or private PyPI'
inputs:
  pypi_pass:
    required: true
    description: 'Password of PyPI repository'

  github_token:
    required: false
    description: 'GitHub token'
    default: 'dummy'
  pypi_name:
    required: false
    description: 'Name of PyPI repository'
    default: 'pypi'
  pypi_host:
    required: false
    description: 'Host of PyPI repository'
    default: 'https://upload.pypi.org/legacy/'
  pypi_user:
    required: false
    description: 'Username of PyPI repository'
    default: '__token__'

runs:
  using: 'composite'
  steps:
  - id: install-tools
    shell: bash
    run: python3 -m pip install --upgrade twine

  - id: setup-pypirc
    shell: bash
    env:
      pypi_name: ${{ inputs.pypi_name }}
      pypi_host: ${{ inputs.pypi_host }}
      pypi_user: ${{ inputs.pypi_user }}
      pypi_pass: ${{ inputs.pypi_pass }}
    run: |
      echo "[distutils]
      index-servers=
          $pypi_name

      [$pypi_name]
      repository: https://$pypi_host
      username: $pypi_user
      password: $pypi_pass
      " > ~/.pypirc

  - id: upload
    shell: bash
    run: python3 -m twine upload --repository ${{ inputs.pypi_name }} --skip-existing --disable-progress-bar dist/*
